# IMPORT THE DEPENDECIES

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Loading the dataset to a Pandas DataFrame

In [3]:
credit_card_data = pd.read_csv('creditcard.csv')

In [4]:
# First 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [6]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [8]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26       284807 non-null float64
V27       284807 non-null float64
V28       284807 non-null float64
Amount    284807 non-null float64
Class     284807 non-null int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [13]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

**This Dataset is highly unbalanced**

0 -> Normal Transaction
1 - > Fraudulent transaction

In [11]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [15]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [16]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [17]:
# Compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

* Under-Sampling

**Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions**

**Number of Fraudulent Transactions ---> 492**

In [18]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
80327,58435.0,1.301878,-0.696179,1.103964,-0.692570,-1.527621,-0.516588,-1.083224,0.041819,-0.736772,...,0.456436,1.238856,-0.102035,0.590869,0.381002,-0.081499,0.035331,0.020021,19.95,0
120826,75974.0,1.374184,-0.954054,0.280265,-1.507286,-1.074885,-0.365597,-0.730120,-0.081545,-2.477872,...,-0.534463,-1.272519,0.265648,-0.048425,0.003267,-0.635907,0.030017,0.019229,49.00,0
147812,89020.0,2.067661,-0.046104,-1.088676,0.401050,-0.108465,-1.177616,0.186529,-0.334133,0.537324,...,-0.292975,-0.705568,0.332381,-0.022747,-0.288089,0.199618,-0.070352,-0.060529,1.29,0
205695,135872.0,1.732132,-0.615149,-2.787540,0.095866,0.587152,-1.302778,1.110222,-0.503295,0.030510,...,0.424755,0.907715,-0.415118,-0.317418,0.640327,0.448804,-0.149243,-0.071839,206.00,0
268934,163455.0,-2.810407,-2.171612,-1.114326,1.195771,2.256315,-2.485102,0.798788,0.050050,-1.148018,...,0.643173,0.318514,0.114304,-0.012522,0.929108,-0.443972,-0.194367,-0.539806,243.00,0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [22]:
new_dataset['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [23]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97093.837398,-0.100973,-0.095842,0.007031,-0.047578,-0.010086,0.007388,0.040854,-0.131919,0.006969,...,0.016110,-0.013477,-0.024593,0.054114,0.009875,-0.020071,0.021169,0.005225,0.003056,107.859858
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features & Targets

In [24]:
X = new_dataset.drop(columns = 'Class', axis=1)
Y = new_dataset['Class']

In [25]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
80327    58435.0  1.301878 -0.696179  1.103964 -0.692570 -1.527621 -0.516588
120826   75974.0  1.374184 -0.954054  0.280265 -1.507286 -1.074885 -0.365597
147812   89020.0  2.067661 -0.046104 -1.088676  0.401050 -0.108465 -1.177616
205695  135872.0  1.732132 -0.615149 -2.787540  0.095866  0.587152 -1.302778
268934  163455.0 -2.810407 -2.171612 -1.114326  1.195771  2.256315 -2.485102
25948    33840.0  1.357514 -0.816758  0.624215 -0.929920 -1.084734  0.087735
55747    47106.0 -0.790368  0.455313  1.998548 -1.959428 -0.451010 -0.485361
155914  106784.0 -0.489923  0.847257  2.411425 -0.109171  0.125655 -0.359780
274094  165847.0  1.767082 -1.227225 -1.099232 -1.918915 -0.811343 -0.825275
103100   68496.0  0.915633 -0.782551  0.975638  0.129565 -0.938291  0.755437
217284  140837.0  1.968443  0.188058 -1.973364  1.052574  0.826531 -0.688309
132916   80170.0 -1.079903 -0.214276  1.835885  1.210586  0.858514 -0.580900
233799  147709.0 -0.699563 -0.431849  0.608221  0.157439 -0.024135 -0.857326
85682    60882.0  1.007245 -0.317884  1.325466  1.279637 -1.096319  0.171938
239365  150071.0 -2.329879  0.402720 -1.639064 -1.799518  3.069019  2.982133
55928    47192.0  1.356486 -0.523475  0.309833 -0.751164 -0.871755 -0.469508
273917  165763.0  1.858380 -0.571740 -1.262324 -0.012688 -0.316216 -1.032722
72851    54883.0 -1.588151  1.632553  0.702978 -0.106200 -0.608085 -0.708602
279138  168671.0  2.127544 -0.037217 -1.529296  0.121500  0.531950 -0.351658
168411  119215.0 -0.215225  0.928313 -0.323512 -0.963821  1.092612 -1.263482
94177    64765.0  1.233520 -0.233575  0.455534  0.378623 -0.848867 -0.774562
193479  130155.0  0.206462  1.001640  0.148920  0.989258  1.098716 -0.238154
284270  172288.0  2.115284 -0.082377 -1.957912  0.320948  0.474195 -0.864339
71306    54249.0 -1.921743  1.418881  0.895700  1.534260 -0.859002  1.121674
258916  158877.0 -0.490715 -0.559513  0.585881 -1.659439 -0.262042  0.631567
174039  121737.0 -1.426830  0.866512 -0.797662 -1.430469  1.031104  0.004851
89084    62418.0  0.877614 -0.223856  0.245040  1.196033 -0.268269 -0.047874
143116   85128.0 -3.697755  1.722838 -0.817637  0.532834 -2.106346 -0.484828
231974  146997.0  2.013706 -0.183753 -1.396778  0.201014  0.053106 -0.836658
27411    34540.0 -1.308839  0.160736  1.393789 -0.423298 -0.705498 -0.600810
...          ...       ...       ...       ...       ...       ...       ...
251891  155548.0  1.878230  1.325630 -2.333469  4.233151  1.355184 -0.853508
251904  155554.0 -1.040067  3.106703 -5.409027  3.109903 -0.887237 -2.497522
252124  155662.0 -1.928613  4.601506 -7.124053  5.716088  1.026579 -3.189073
252774  155965.0 -1.201398  4.864535 -8.328823  7.652399 -0.167445 -2.767695
254344  156685.0 -0.129778  0.141547 -0.894702 -0.457662  0.810608 -0.504723
254395  156710.0  0.202402  1.176270  0.346379  2.882138  1.407133 -0.504355
255403  157207.0  1.170756  2.501038 -4.986159  5.374160  0.997798 -1.259004
255556  157284.0 -0.242245  4.147186 -5.672349  6.493741  1.591168 -1.602523
258403  158638.0 -5.976119 -7.196980 -5.388316  5.104799  4.676533 -5.566870
261056  159844.0 -0.408111  3.132944 -3.098030  5.803893  0.890609 -0.501474
261473  160034.0 -2.349340  1.512604 -2.647497  1.753792  0.406328 -2.188494
261925  160243.0 -2.783865  1.596824 -2.084844  2.512986 -1.446749 -0.828496
262560  160537.0  0.567539  3.309385 -6.631268  6.394574 -0.054172 -2.396535
262826  160665.0 -0.417340  4.700055 -7.521767  7.671884  0.260821 -2.646693
263080  160791.0  2.132386  0.705608 -3.530759  0.514779  1.527175 -1.716268
263274  160870.0 -0.644278  5.002352 -8.252739  7.756915 -0.216267 -2.751496
263324  160895.0 -0.848290  2.719882 -6.199070  3.044437 -3.301910 -1.992117
263877  161154.0 -3.387601  3.977881 -6.978585  1.657766 -1.100500 -3.599487
268375  163181.0 -5.238808  0.623013 -5.784507  1.678889 -0.364432 -0.477295
272521  165132.0 -7.503926 -0.360628 -3.830952  2.486103  2.497367  1.332437
274382  165981.0 -5.766879 -8.402154  0.056543  6.950983  9.880564 -5.773192
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598
275992  166831.0 -2.027135 -1.131890 -1.135194  1.086963 -0.010547  0.423797
276071  166883.0  2.091900 -0.757459 -1.192258 -0.755458 -0.620324 -0.322077
276864  167338.0 -1.374424  2.793185 -4.346572  2.400731 -1.688433  0.111136
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7         V8        V9  ...       V20       V21       V22  \
80327  -1.083224   0.041819 -0.736772  ...  0.138228  0.456436  1.238856
120826 -0.730120  -0.081545 -2.477872  ... -0.221971 -0.534463 -1.272519
147812  0.186529  -0.334133  0.537324  ... -0.219854 -0.292975 -0.705568
205695  1.110222  -0.503295  0.030510  ...  0.093336  0.424755  0.907715
268934  0.798788   0.050050 -1.148018  ...  1.057446  0.643173  0.318514
25948  -1.149957   0.156528 -0.539678  ...  0.140884  0.382516  0.967727
55747   0.087593  -0.063345 -1.180861  ...  0.290397  0.293476  0.843174
155914  0.543145  -0.284868  1.492760  ...  0.069301 -0.307376 -0.420344
274094 -0.216196  -0.119441  2.344188  ...  0.096968 -0.248836 -0.750526
103100 -0.886169   0.477144  0.781263  ...  0.008495  0.223316  0.578770
217284  0.663090  -0.254038 -0.363781  ... -0.218869  0.188027  0.499422
132916 -0.352215   0.365000 -0.608029  ...  0.223401  0.005071 -0.378398
233799  0.824180  -0.385128  0.281531  ... -0.310136  0.055491  0.462970
85682  -0.834520   0.305801  0.850359  ... -0.116544  0.296428  0.752753
239365 -0.368295   1.746172 -0.397648  ... -0.312060 -0.183626 -0.884449
55928  -0.555097  -0.109737 -1.137095  ... -0.378950 -0.205150 -0.086852
273917  0.213776  -0.350084  1.438383  ... -0.042414  0.181674  0.725951
72851  -0.092092   0.868388 -0.814349  ...  0.010663 -0.110705 -0.474391
279138  0.146425  -0.221015  0.498991  ... -0.136852 -0.338742 -0.849642
168411  1.280830  -0.290278  0.066804  ... -0.177418  0.134861  0.615053
94177  -0.193802  -0.078181 -1.339654  ... -0.531509 -0.759469 -1.902947
193479  1.030908  -0.681289 -0.251720  ...  0.382089 -0.311719 -0.437451
284270  0.376891  -0.255545  0.857088  ... -0.347489 -0.051421 -0.011767
71306  -1.166439   1.683649  0.328776  ... -0.256009 -0.284607 -0.700839
258916  0.274289   0.064727 -0.948603  ...  0.098944 -0.079309 -0.213545
174039  1.524817  -0.185037  0.441952  ... -0.276837 -0.467037 -0.233477
89084   0.105886   0.074215 -0.224865  ...  0.093011  0.229051  0.369881
143116 -1.022925   2.157383 -0.064431  ... -0.170526  0.135023  0.242087
231974  0.076555  -0.188802  0.496644  ... -0.227846  0.293712  0.909169
27411   0.272009   0.432775 -2.115920  ... -0.317033 -0.146692 -0.500579
...          ...        ...       ...  ...       ...       ...       ...
251891  0.716025  -0.164910 -1.502345  ... -0.226108 -0.152131 -0.360736
251904 -2.073347   0.639818 -3.013331  ...  1.054390  0.773961  0.214868
252124 -2.261897   1.185096 -4.441942  ...  0.328796  0.602291 -0.541287
252774 -3.176421   1.623279 -4.367228  ...  0.597026  0.532320 -0.556913
254344  1.373588  -0.209476  0.208494  ...  0.399447 -0.032643 -0.246526
254395  1.438537  -0.395603 -1.555142  ... -0.206239  0.242560  0.841230
255403 -1.237689   0.358426 -2.612489  ...  0.227618  0.123145 -0.713201
255556 -0.950463   0.722903 -4.128505  ...  0.562030  0.249023 -0.480286
258403 -4.291180   0.876531 -1.075478  ...  3.136338  1.459369 -0.136262
261056 -0.440054   0.591828 -3.267693  ...  0.499568  0.098482 -0.538375
261473 -0.686935  -0.547984 -0.099528  ... -0.093421 -0.088519 -0.595178
261925 -0.732262  -0.203329 -0.347046  ... -0.515001  0.203563  0.293268
262560 -2.792489   0.514811 -3.541780  ...  0.555412  0.614221 -0.365047
262826 -2.854432   0.958783 -4.588536  ...  0.832035  0.622200 -0.437708
263080  1.132791  -0.574214  0.128904  ... -0.211167  0.163739  0.703910
263274 -3.358857   1.406268 -4.403852  ...  0.816558  0.587728 -0.605759
263324 -3.734902   1.520079 -2.548788  ...  0.319576  1.125229  0.805258
263877 -3.686651   1.942252 -3.065089  ... -0.004301  1.043587  0.262189
268375 -4.276132  -0.695173 -2.971644  ... -0.203270 -0.326140  1.509239
272521 -6.783964 -15.415385  0.465512  ... -0.475126 -6.389132  2.249964
274382 -5.748879   0.721743 -1.076274  ...  2.493224  0.880395 -0.130436
274475 -0.055178   0.277831 -1.745854  ...  0.190877  0.473211  0.719400
275992  3.790880  -1.155595 -0.063434  ...  0.033804 -0.315105  0.575520
276071 -1.082511   0.117200 -0.140927  ...  0.037438  0.288253  0.831939
276864 -0.922038  -2.149930 -2.027474  ...  0.650196 -0.870779  0.504849
279863 -0.882850   0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170   0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739   1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002   1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050  -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
80327  -0.102035  0.590869  0.381002 -0.081499  0.035331  0.020021   19.95
120826  0.265648 -0.048425  0.003267 -0.635907  0.030017  0.019229   49.00
147812  0.332381 -0.022747 -0.288089  0.199618 -0.070352 -0.060529    1.29
205695 -0.415118 -0.317418  0.640327  0.448804 -0.149243 -0.071839  206.00
268934  0.114304 -0.012522  0.929108 -0.443972 -0.194367 -0.539806  243.00
25948  -0.232563 -0.489350  0.492545 -0.014061  0.026543  0.009264   29.95
55747  -0.465587 -0.059746  0.618975 -0.156424  0.167903  0.115227   13.40
155914 -0.305757 -0.053038  0.268463 -0.730954 -0.078695 -0.145349    2.12
274094  0.186611 -0.365811 -0.280023 -1.266399  0.039673 -0.022716  151.72
103100 -0.048979 -0.217573 -0.032442  1.144245 -0.029947  0.012048   99.00
217284 -0.001591  0.692667  0.417659 -0.536281 -0.046233 -0.062465   34.90
132916  0.315761  0.129747 -0.660395 -0.617699  0.140774  0.166886   14.95
233799  0.100589  0.567469 -1.016081  0.068166 -0.255029  0.007555  158.75
85682  -0.070237  0.051774  0.221559 -0.210049  0.071878  0.046962   64.00
239365 -0.627455  0.607214  0.799082 -0.039950 -0.160484 -0.336176   59.15
55928  -0.085642  0.088289  0.347484  1.158990 -0.053990 -0.003250   16.80
273917 -0.098630  0.046216  0.355502 -0.555592  0.021508 -0.036372  100.00
72851   0.141281  0.321840 -0.098918  0.051717  0.006632  0.029591    9.99
279138  0.277787  0.045316 -0.161027  0.206497 -0.073016 -0.059495    0.89
168411 -0.160628 -0.164055 -0.588291  0.275641  0.174539  0.258657   19.99
94177   0.301482  0.389432  0.055385 -0.881357  0.024995  0.029554   34.30
193479 -0.018189  0.530312 -1.116498  0.444334 -0.377327 -0.200138    6.75
284270  0.054158  0.452607  0.365883 -0.231720 -0.051844 -0.066907    1.00
71306  -0.124297 -0.764160  0.077336 -0.336941 -0.158807 -0.076115    7.69
258916  0.194063  0.214939 -0.968462 -0.624434  0.196639  0.149081  175.66
174039 -0.406118 -1.407149  0.202385  0.006159  0.996960  0.441100  241.10
89084  -0.210474  0.016485  0.504265 -0.281459  0.001636  0.031745  144.00
143116 -0.220337  0.485671 -0.076833  0.365941  0.026370 -0.082455   77.86
231974 -0.060320 -0.314938  0.237157 -0.101247 -0.028231 -0.069131   19.95
27411   0.194365  0.460774  0.033509 -0.635254 -0.044907  0.000312  117.00
...          ...       ...       ...       ...       ...       ...     ...
251891  0.043414 -0.242380  0.171098 -0.002601 -0.026667  0.005238    7.06
251904 -0.184233 -0.284091  0.493467  0.732329  0.675067  0.337076   94.82
252124 -0.354639 -0.701492 -0.030973  0.034070  0.573393  0.294686    0.77
252774  0.192444 -0.698588  0.025003  0.514968  0.378105 -0.053133    0.77
254344  0.484108  0.359637 -0.435972 -0.248480  0.021527  0.109192  187.11
254395 -0.370157 -0.026012  0.491954  0.234576 -0.279788 -0.331933    7.59
255403 -0.080868 -0.964310  0.338568  0.068630  0.481588  0.268226    4.97
255556 -0.286080 -1.153575 -0.035571  0.559628  0.409446  0.221048    0.77
258403  0.848177 -0.269916 -1.095060 -0.710905  0.565846 -1.034107  296.00
261056 -0.217989 -1.042657  0.314389  0.543244  0.233851  0.119603   45.51
261473  0.258148  0.061901 -0.354180 -1.152671 -0.736073  0.733703    4.90
261925  0.199568  0.146868  0.163602 -0.624085 -1.333100  0.428634  156.00
262560 -0.180409 -0.523271  0.645054  0.246466  0.902675  0.473571    4.69
262826 -0.090358 -0.742802 -0.312361  0.502575  0.821390  0.372379    0.77
263080 -0.245076  0.460049  0.920281 -0.216586 -0.026219 -0.025001    1.00
263274  0.033746 -0.756170 -0.008172  0.532772  0.663970  0.192067    0.77
263324  0.199119  0.035206  0.012159  0.601658  0.137468 -0.171397  127.14
263877 -0.479224 -0.326638 -0.156939  0.113807  0.354124  0.287592    0.38
268375 -0.215966 -0.245727  0.893041  0.865758  0.854657 -0.964482   39.98
272521  1.670508  0.140450  0.162147  1.207731  1.268958  0.097538   12.31
274382  2.241471  0.665346 -1.890041 -0.120803  0.073269  0.583799    0.00
274475  0.122458 -0.255650 -0.619259 -0.484280  0.683535  0.443299   39.90
275992  0.490842  0.756502 -0.142685 -0.602777  0.508712 -0.091646  634.30
276071  0.142007  0.592615 -0.196143 -0.136676  0.020182 -0.015470   19.95
276864  0.137994  0.368275  0.103137 -0.414209  0.454982  0.096711  349.08
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [26]:
print(Y)

80327     0
120826    0
147812    0
205695    0
268934    0
25948     0
55747     0
155914    0
274094    0
103100    0
217284    0
132916    0
233799    0
85682     0
239365    0
55928     0
273917    0
72851     0
279138    0
168411    0
94177     0
193479    0
284270    0
71306     0
258916    0
174039    0
89084     0
143116    0
231974    0
27411     0
         ..
251891    1
251904    1
252124    1
252774    1
254344    1
254395    1
255403    1
255556    1
258403    1
261056    1
261473    1
261925    1
262560    1
262826    1
263080    1
263274    1
263324    1
263877    1
268375    1
272521    1
274382    1
274475    1
275992    1
276071    1
276864    1
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into Training data and Testing Data